# -----------------------------------------------------------------------------
# 04_snapshot.R — lock the environment and record provenance.
#
# Run from the project root, AFTER 03_install_packages.R reports PASS:
#   Rscript scripts/00_setup/04_snapshot.R
#
# Writes:
#   renv.lock                      package versions (the reproducibility contract)
#   data/metadata/session_info.txt full session record
#   data/metadata/environment.yml  machine-readable environment provenance
# -----------------------------------------------------------------------------

stopifnot(file.exists(".gitignore"))
dir.create("data/metadata", showWarnings = FALSE, recursive = TRUE)

cat("=== renv::snapshot ===\n")
# type = "all" pins every installed package, not just those renv detects in
# code. Deliberate: dependency-inference misses packages used via :: inside
# strings or loaded conditionally, and a partial lockfile is a reproducibility
# hole that only shows up on someone else's machine.
renv::snapshot(type = "all", prompt = FALSE)

lock <- jsonlite::fromJSON("renv.lock")
cat("packages locked:", length(lock$Packages), "\n")
cat("R version in lock:", lock$R$Version, "\n")

cat("\n=== session info ===\n")
si <- sessioninfo::session_info(pkgs = "installed", include_base = TRUE)
print(si)
capture.output(print(si), file = "data/metadata/session_info.txt")

# --- machine-readable environment provenance ---------------------------------
osr <- tryCatch(readLines("/etc/os-release", warn = FALSE), error = function(e) character(0))
pretty_name <- sub('^PRETTY_NAME="?([^"]*)"?$', "\\1", grep("^PRETTY_NAME=", osr, value = TRUE))

env <- c(
  "# Environment provenance — regenerated by scripts/00_setup/04_snapshot.R",
  paste0("recorded:        ", format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z")),
  paste0("os:              ", if (length(pretty_name)) pretty_name else "unknown"),
  paste0("platform:        ", R.version$platform),
  paste0("r_version:       ", as.character(getRversion())),
  paste0("bioc_version:    ", as.character(BiocManager::version())),
  paste0("renv_version:    ", as.character(packageVersion("renv"))),
  paste0("n_packages:      ", length(lock$Packages)),
  paste0("genome_build:    hg19   # project-wide; asserted at every coordinate step"),
  "repositories:",
  paste0("  CRAN:          ", getOption("repos")[["CRAN"]]),
  paste0("  BioCsoft:      ", getOption("repos")[["BioCsoft"]]),
  "notes:",
  "  - Bioconductor served from the GWDG mirror because bioconductor.org is",
  "    unroutable from this network (decision log D-006). Content is identical",
  "    to upstream; substitute freely if your network can reach bioconductor.org.",
  "  - CRAN served as Ubuntu-noble binaries from Posit P3M (D-007). .Rprofile",
  "    falls back to cloud.r-project.org on any non-noble platform."
)
writeLines(env, "data/metadata/environment.yml")

cat("\nwrote data/metadata/session_info.txt\n")
cat("wrote data/metadata/environment.yml\n")
cat("wrote renv.lock\n")
cat("\nRESULT: environment locked.\n")
